sudo: false
language: python
cache: pip
script: tox
python:
  - 2.7
  - 3.4
  - 3.5
  - 3.6
  - pypy
install: travis_retry pip install tox-travis
services:
  - mongodb
  - redis-server
before_script:
  - sleep 15
  - mongo eve_test --eval 'db.createUser({user:"test_user",pwd:"test_pw",roles:["readWrite"]});'
